version: '3.7'

x-env: &env production
x-decidim: &decidim 0.23.1
x-ruby: &ruby 
  RUBY_VERSION: 2.6.6
x-pg-env: &pg-env
  POSTGRES_USER: &pg-user postgres
  POSTGRES_PASSWORD:
  POSTGRES_DB: &pg-db azione-decidim_production
  POSTGRES_HOST_AUTH_METHOD: trust

x-admin: &admin
  ADMIN_EMAIL: &admin_email patrick.jusic@uspace.it
  ADMIN_PASSWORD: azione_decidim
x-org: &org
  ORG_NAME: &org_name PartecipAzione
  ORG_HOST: &org_host partecip.azione.it
  ORG_ADMIN: &org_admin patrickjusic96@gmail.com

x-smtp: &smtp
  SMTP_HOST: &smtp_host in-v3.mailjet.com 
  SMTP_PORT: 25
  SMTP_DOMAIN: uspace.it
  SMTP_ADDRESS: *smtp_host
  SMTP_USERNAME: 657288d8a677f13ab927ac92562fb967
  SMTP_PASSWORD: 2f8bfff90441f4123af9eed6c3587f33

x-network: &network
  networks:
    decidim:

services:
  decidim:
    container_name: decidim
    hostname: decidim-host
    image: *pg-db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - decidim-gems:/usr/local/bundle:delegated
      - decidim-config:/home/decidim/azione-decidim/config
    environment:
      PORT: 3000
      DATABASE_HOST: pg
      DATABASE_USERNAME: *pg-user
      DATABASE_NAME: *pg-db
      RAILS_ENV: *env
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgres://postgres@pg:5432/azione-decidim_production
      RAILS_SERVE_STATIC_FILES: "true"
      SECRETKEY: secret
      SECRET_KEY_BASE: secret
      DECIDIM_VERSION: *decidim
      # RAILS_LOG_TO_STDOUT: true
      <<: [*ruby, *admin, *org, *smtp]
    depends_on:
      - pg
      - redis
      - nginx
    links:
      - pg
      - redis
    <<: *network

  pg:
    image: postgres
    container_name: pg
    volumes:
      - pg:/var/lib/postgresql/data
    environment:
      <<: *pg-env
    <<: *network

  redis:
    container_name: redis_decidim
    image: redis
    volumes:
      - redis:/data
    <<: *network

  mailer:
    image: namshi/smtp
    container_name: mailer
    restart: always
    <<: *network
      
  nginx:
    image: bunkerity/bunkerized-nginx
    container_name: nginx
    restart: always
    ports:
      - 80:8080
      - 443:8443
    environment:
      # GENERATE_SELF_SIGNED_SSL: "yes"
      # AUTO_LETS_ENCRYPT: "yes" 
      # REDIRECT_HTTP_TO_HTTPS: "yes"

      # SERVER_NAME: *org_host
      SERVER_NAME: partecip.azione.it
      DISABLE_DEFAULT_SERVER: "yes"
      ALLOWED_METHODS: "GET|POST|HEAD|OPTIONS|PUT|DELETE"
      WRITE_ACCESS: "yes"
      REFERRER_POLICY: "origin"
      USE_CLAMAV_UPLOAD: "no"
      USE_CLAMAV_SCAN: "no"
      CLAMAV_SCAN_REMOVE: "no"
      ADDITIONAL_MODULES: "ruby"
      USE_MODSECURITY_CRS: "no"
    volumes:
      - nginx-letsencrypt:/etc/letsencrypt
      - ./server-confs:/server-confs
      - ./http-confs:/http-confs
    <<: *network 

volumes:
  pg:
  redis:
  decidim-gems:
  decidim-config:
  nginx-letsencrypt:

networks:
  decidim:
