# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Graphite
    orgId: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  isDefault: true
  url: http://prometheus:9090
  
- name: Postgres
  type: postgres
  access: proxy
  url: http://postgres:5432
  database: azione-decidim_production 
  user: postgres
  # secureJsonData:
  #   password: password
  jsonData:
    sslmode: "disable"